"""add scopes table and many-to-many relation

Revision ID: 04fa5ea39ed0
Revises: 6bc3864fa3ba
Create Date: 2026-06-25 22:27:27.529768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fa5ea39ed0'
down_revision: Union[str, Sequence[str], None] = '6bc3864fa3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
